---
# Setup server
# =============================================

- name: update apt
  action: command /usr/bin/apt-get update
  sudo: true

- name: update cache 
  apt: update_cache=yes
  sudo: true

- name: Install essential packages
  apt: pkg=$item
  with_items:
    - build-essential
    - python-dev
    - python-setuptools
    - git
    - curl

- name: install java
  apt: pkg=openjdk-7-jre update-cache=yes
  
# Install Scala
# =============================================

- name: get scala
  command: wget http://www.scala-lang.org/downloads/distrib/files/scala-${scala_version}.tgz

- name: tar
  command: tar zxf scala-${scala_version}.tgz

- name: move scala to local
  command: sudo mv scala-${scala_version} /usr/share/scala
  ignore_errors: yes

# Symbolic linking
# =============================================

- name: link scala
  command: sudo ln -s /usr/share/scala/bin/scala /usr/bin/scala
  ignore_errors: yes

- name: link scalac
  command: sudo ln -s /usr/share/scala/bin/scalac /usr/bin/scalac
  ignore_errors: yes

- name: link fsc
  command: sudo ln -s /usr/share/scala/bin/fsc /usr/bin/fsc
  ignore_errors: yes

- name: link scaladoc
  command: sudo ln -s /usr/share/scala/bin/scaladoc /usr/bin/scaladoc
  ignore_errors: yes

- name: link scaladoc
  command: sudo ln -s /usr/share/scala/bin/scalap /usr/bin/scalap
  ignore_errors: yes
  
# =============================================

- name: Install Unzip
  action: apt pkg=unzip state=latest install_recommends=yes
     
- name: download
  command: sudo wget http://downloads.typesafe.com/play/2.1.2/play-2.1.2.zip
  
- name: unzip
  command: sudo unsizp play-2.1.2.zip 
  
- name: clean up
  command: sudo rm -rf play-2.1.2.zip
  
- name: move to local
  command: sudo mv play-2.1.2.zip /usr/local/play